name: Tests  # Имя workflow, которое будет отображаться в разделе "Actions" на GitHub

on:
  push:
    branches: [ "main" ]  # Workflow запускается при каждом пуше в ветку main
  pull_request:
    branches: [ "main" ]  # Workflow запускается при каждом pull request в ветку main

permissions:
  contents: read  # Устанавливает минимальные разрешения для чтения содержимого репозитория

jobs:
  runt-test:  # Задание для запуска тестов
    runs-on: ubuntu-latest  # Рабочее окружение, используемое для выполнения задания (Ubuntu)

    steps:
      - uses: actions/checkout@v4  # Шаг для клонирования репозитория на рабочую машину
      - name: Set up Python 3.11  # Устанавливает Python версии 3.11
        uses: actions/setup-python@v3  # Используется официальный action для настройки Python
        with:
          python-version: "3.11"  # Версия Python, которая будет установлена

      - name: Install dependencies  # Устанавливает зависимости из файла requirements.txt
        run: |
          python -m pip install --upgrade pip  # Обновляет pip
          pip install -r requirements.txt  # Устанавливает зависимости проекта

      - name: Run tests with coverage  # Запуск тестов с измерением покрытия кода
        run: |
          coverage run -m unittest discover -s tests -v  # Запускает тесты с модулем coverage
          coverage report  # Показывает отчет по покрытию
          coverage xml  # Генерирует отчет в формате XML для последующей отправки

      - name: Submit coverage to Coveralls  # Отправка отчета о покрытии кода в Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}  # Токен для аутентификации в Coveralls
        run: coveralls  # Отправляет данные покрытия кода на платформу Coveralls

  sonarcloud:  # Задание для запуска анализа с SonarCloud
    runs-on: ubuntu-latest  # Рабочее окружение на Ubuntu

    steps:
      - uses: actions/checkout@v4  # Клонирование репозитория на рабочую машину
        with:
          fetch-depth: 0  # Клонирует всю историю репозитория для правильного анализа SonarCloud

      - name: SonarCloud Scan  # Запуск сканирования SonarCloud
        uses: sonarsource/sonarcloud-github-action@v3.1.0  # Официальный action для запуска анализа SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Токен для аутентификации в SonarCloud, хранится в секрете
